version: '3.3'

services:
  website:
    build:
      context: ./
      dockerfile: Dockerfile
    image: www-ricardo/latest
    ports:
      - "8080:8080"
    volumes:
    - ./src/:/home/node/www/src/
